package it.giaquinto.springberry.model.raspberry.pin;

public enum BusPin {
    I2C_INTER_INTEGRATED_CIRCUIT,
    UART_UNIVERSAL_ASYNCHRONOUS_RECEIVER_TRANSMITTER,

    SPI_SERIAL_PERIPHERAL_INTERFACE,

    PCM_PULSE_CODE_MODULATION,

    PWM,

    GPCLK,

    NO_PROTOCOL;
}
